### ISSUE TITLE
Play local music 

### ISSUE THREAD

**Issue by Tetsunna** [bpolat/Music-Player#4]
Hi,

How can i play a music from appel music directory ? 

Best regard

**Comment by bpolat** [comment]
hello you cannot play from apple music directory.



On Jul 10, 2017, at 6:02 PM, Tetsunna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

How can i play a music from appel music directory ?

Best regard

**Comment by Tetsunna** [comment]
Ok ty
